# Generated by Django 5.0.2 on 2024-02-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Viewers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.TextField(max_length=500)),
                ('Viewers', models.ManyToManyField(blank=True, to='Viewers.viewer')),
            ],
        ),
    ]
